const QuizLens = artifacts.require("QuizLens");
const fs = require("fs");
const path = require("path");

module.exports = function(deployer) {
  deployer.deploy(QuizLens).then(async (instance) => {
    console.log("✅ QuizLens deployed to:", instance.address);
    
    // Write address to frontend config
    const config = `// Auto-generated by Truffle migration — do not edit manually\nconst CONTRACT_ADDRESS = "${instance.address}";\n`;
    const outPath = path.join(__dirname, "../frontend/contract_address.js");
    fs.writeFileSync(outPath, config);
    console.log("✅ Address written to frontend/contract_address.js");
    console.log("\nNext: open frontend/index.html in your browser and connect MetaMask.");
  });
};
